/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProjectExportWithTestPlansPostModel
 */
public class ProjectExportWithTestPlansPostModelTest {
    private final ProjectExportWithTestPlansPostModel model = new ProjectExportWithTestPlansPostModel();

    /**
     * Model tests for ProjectExportWithTestPlansPostModel
     */
    @Test
    public void testProjectExportWithTestPlansPostModel() {
        // TODO: test ProjectExportWithTestPlansPostModel
    }

    /**
     * Test the property 'testPlansIds'
     */
    @Test
    public void testPlansIdsTest() {
        // TODO: test testPlansIds
    }

}
