/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.client.model.ParameterShortModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicTestPointModel
 */
public class PublicTestPointModelTest {
    private final PublicTestPointModel model = new PublicTestPointModel();

    /**
     * Model tests for PublicTestPointModel
     */
    @Test
    public void testPublicTestPointModel() {
        // TODO: test PublicTestPointModel
    }

    /**
     * Test the property 'configurationId'
     */
    @Test
    public void configurationIdTest() {
        // TODO: test configurationId
    }

    /**
     * Test the property 'configurationGlobalId'
     */
    @Test
    public void configurationGlobalIdTest() {
        // TODO: test configurationGlobalId
    }

    /**
     * Test the property 'autoTestIds'
     */
    @Test
    public void autoTestIdsTest() {
        // TODO: test autoTestIds
    }

    /**
     * Test the property 'iterationId'
     */
    @Test
    public void iterationIdTest() {
        // TODO: test iterationId
    }

    /**
     * Test the property 'parameterModels'
     */
    @Test
    public void parameterModelsTest() {
        // TODO: test parameterModels
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
