/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.client.model.ExternalLinkModel;
import ru.testit.client.model.LinkModel;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TestPlanLink
 */
public class TestPlanLinkTest {
    private final TestPlanLink model = new TestPlanLink();

    /**
     * Model tests for TestPlanLink
     */
    @Test
    public void testTestPlanLink() {
        // TODO: test TestPlanLink
    }

    /**
     * Test the property 'bugLink'
     */
    @Test
    public void bugLinkTest() {
        // TODO: test bugLink
    }

    /**
     * Test the property 'workItemGlobalId'
     */
    @Test
    public void workItemGlobalIdTest() {
        // TODO: test workItemGlobalId
    }

    /**
     * Test the property 'workItemName'
     */
    @Test
    public void workItemNameTest() {
        // TODO: test workItemName
    }

    /**
     * Test the property 'configurationName'
     */
    @Test
    public void configurationNameTest() {
        // TODO: test configurationName
    }

    /**
     * Test the property 'createdById'
     */
    @Test
    public void createdByIdTest() {
        // TODO: test createdById
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

}
