/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.client.model.WorkItemLocalSelectModelExtractionModel;
import ru.testit.client.model.WorkItemLocalSelectModelFilter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkItemGroupGetModelSelectModel
 */
public class WorkItemGroupGetModelSelectModelTest {
    private final WorkItemGroupGetModelSelectModel model = new WorkItemGroupGetModelSelectModel();

    /**
     * Model tests for WorkItemGroupGetModelSelectModel
     */
    @Test
    public void testWorkItemGroupGetModelSelectModel() {
        // TODO: test WorkItemGroupGetModelSelectModel
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'extractionModel'
     */
    @Test
    public void extractionModelTest() {
        // TODO: test extractionModel
    }

}
