/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.client.model.TestPointFilterModelCreatedDate;
import ru.testit.client.model.TestPointFilterModelDuration;
import ru.testit.client.model.TestPointFilterModelModifiedDate;
import ru.testit.client.model.TestPointFilterModelWorkItemCreatedDate;
import ru.testit.client.model.TestPointFilterModelWorkItemModifiedDate;
import ru.testit.client.model.TestPointStatus;
import ru.testit.client.model.WorkItemPriorityModel;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import ru.testit.client.invoker.JSON;

/**
 * ApiV2TestPointsSearchPostRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ApiV2TestPointsSearchPostRequest {
  public static final String SERIALIZED_NAME_TEST_PLAN_IDS = "testPlanIds";
  @SerializedName(SERIALIZED_NAME_TEST_PLAN_IDS)
  private Set<UUID> testPlanIds;

  public static final String SERIALIZED_NAME_TEST_SUITE_IDS = "testSuiteIds";
  @SerializedName(SERIALIZED_NAME_TEST_SUITE_IDS)
  private Set<UUID> testSuiteIds;

  public static final String SERIALIZED_NAME_WORK_ITEM_GLOBAL_IDS = "workItemGlobalIds";
  @SerializedName(SERIALIZED_NAME_WORK_ITEM_GLOBAL_IDS)
  private Set<Long> workItemGlobalIds;

  public static final String SERIALIZED_NAME_STATUSES = "statuses";
  @SerializedName(SERIALIZED_NAME_STATUSES)
  private Set<TestPointStatus> statuses;

  public static final String SERIALIZED_NAME_PRIORITIES = "priorities";
  @SerializedName(SERIALIZED_NAME_PRIORITIES)
  private Set<WorkItemPriorityModel> priorities;

  public static final String SERIALIZED_NAME_IS_AUTOMATED = "isAutomated";
  @SerializedName(SERIALIZED_NAME_IS_AUTOMATED)
  private Boolean isAutomated;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CONFIGURATION_IDS = "configurationIds";
  @SerializedName(SERIALIZED_NAME_CONFIGURATION_IDS)
  private Set<UUID> configurationIds;

  public static final String SERIALIZED_NAME_TESTER_IDS = "testerIds";
  @SerializedName(SERIALIZED_NAME_TESTER_IDS)
  private Set<UUID> testerIds;

  public static final String SERIALIZED_NAME_DURATION = "duration";
  @SerializedName(SERIALIZED_NAME_DURATION)
  private TestPointFilterModelDuration duration;

  public static final String SERIALIZED_NAME_SECTION_IDS = "sectionIds";
  @SerializedName(SERIALIZED_NAME_SECTION_IDS)
  private Set<UUID> sectionIds;

  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  private TestPointFilterModelCreatedDate createdDate;

  public static final String SERIALIZED_NAME_CREATED_BY_IDS = "createdByIds";
  @SerializedName(SERIALIZED_NAME_CREATED_BY_IDS)
  private Set<UUID> createdByIds;

  public static final String SERIALIZED_NAME_MODIFIED_DATE = "modifiedDate";
  @SerializedName(SERIALIZED_NAME_MODIFIED_DATE)
  private TestPointFilterModelModifiedDate modifiedDate;

  public static final String SERIALIZED_NAME_MODIFIED_BY_IDS = "modifiedByIds";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY_IDS)
  private Set<UUID> modifiedByIds;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private Set<String> tags;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Map<String, Set<String>> attributes;

  public static final String SERIALIZED_NAME_WORK_ITEM_CREATED_DATE = "workItemCreatedDate";
  @SerializedName(SERIALIZED_NAME_WORK_ITEM_CREATED_DATE)
  private TestPointFilterModelWorkItemCreatedDate workItemCreatedDate;

  public static final String SERIALIZED_NAME_WORK_ITEM_CREATED_BY_IDS = "workItemCreatedByIds";
  @SerializedName(SERIALIZED_NAME_WORK_ITEM_CREATED_BY_IDS)
  private Set<UUID> workItemCreatedByIds;

  public static final String SERIALIZED_NAME_WORK_ITEM_MODIFIED_DATE = "workItemModifiedDate";
  @SerializedName(SERIALIZED_NAME_WORK_ITEM_MODIFIED_DATE)
  private TestPointFilterModelWorkItemModifiedDate workItemModifiedDate;

  public static final String SERIALIZED_NAME_WORK_ITEM_MODIFIED_BY_IDS = "workItemModifiedByIds";
  @SerializedName(SERIALIZED_NAME_WORK_ITEM_MODIFIED_BY_IDS)
  private Set<UUID> workItemModifiedByIds;

  public ApiV2TestPointsSearchPostRequest() {
  }

  public ApiV2TestPointsSearchPostRequest testPlanIds(Set<UUID> testPlanIds) {
    
    this.testPlanIds = testPlanIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addTestPlanIdsItem(UUID testPlanIdsItem) {
    if (this.testPlanIds == null) {
      this.testPlanIds = new LinkedHashSet<>();
    }
    this.testPlanIds.add(testPlanIdsItem);
    return this;
  }

   /**
   * Specifies a test point test plan IDS to search for
   * @return testPlanIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getTestPlanIds() {
    return testPlanIds;
  }


  public void setTestPlanIds(Set<UUID> testPlanIds) {
    this.testPlanIds = testPlanIds;
  }


  public ApiV2TestPointsSearchPostRequest testSuiteIds(Set<UUID> testSuiteIds) {
    
    this.testSuiteIds = testSuiteIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addTestSuiteIdsItem(UUID testSuiteIdsItem) {
    if (this.testSuiteIds == null) {
      this.testSuiteIds = new LinkedHashSet<>();
    }
    this.testSuiteIds.add(testSuiteIdsItem);
    return this;
  }

   /**
   * Specifies a test point test suite IDs to search for
   * @return testSuiteIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getTestSuiteIds() {
    return testSuiteIds;
  }


  public void setTestSuiteIds(Set<UUID> testSuiteIds) {
    this.testSuiteIds = testSuiteIds;
  }


  public ApiV2TestPointsSearchPostRequest workItemGlobalIds(Set<Long> workItemGlobalIds) {
    
    this.workItemGlobalIds = workItemGlobalIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addWorkItemGlobalIdsItem(Long workItemGlobalIdsItem) {
    if (this.workItemGlobalIds == null) {
      this.workItemGlobalIds = new LinkedHashSet<>();
    }
    this.workItemGlobalIds.add(workItemGlobalIdsItem);
    return this;
  }

   /**
   * Specifies a test point work item global IDs to search for
   * @return workItemGlobalIds
  **/
  @javax.annotation.Nullable
  public Set<Long> getWorkItemGlobalIds() {
    return workItemGlobalIds;
  }


  public void setWorkItemGlobalIds(Set<Long> workItemGlobalIds) {
    this.workItemGlobalIds = workItemGlobalIds;
  }


  public ApiV2TestPointsSearchPostRequest statuses(Set<TestPointStatus> statuses) {
    
    this.statuses = statuses;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addStatusesItem(TestPointStatus statusesItem) {
    if (this.statuses == null) {
      this.statuses = new LinkedHashSet<>();
    }
    this.statuses.add(statusesItem);
    return this;
  }

   /**
   * Specifies a test point statuses to search for
   * @return statuses
  **/
  @javax.annotation.Nullable
  public Set<TestPointStatus> getStatuses() {
    return statuses;
  }


  public void setStatuses(Set<TestPointStatus> statuses) {
    this.statuses = statuses;
  }


  public ApiV2TestPointsSearchPostRequest priorities(Set<WorkItemPriorityModel> priorities) {
    
    this.priorities = priorities;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addPrioritiesItem(WorkItemPriorityModel prioritiesItem) {
    if (this.priorities == null) {
      this.priorities = new LinkedHashSet<>();
    }
    this.priorities.add(prioritiesItem);
    return this;
  }

   /**
   * Specifies a test point priorities to search for
   * @return priorities
  **/
  @javax.annotation.Nullable
  public Set<WorkItemPriorityModel> getPriorities() {
    return priorities;
  }


  public void setPriorities(Set<WorkItemPriorityModel> priorities) {
    this.priorities = priorities;
  }


  public ApiV2TestPointsSearchPostRequest isAutomated(Boolean isAutomated) {
    
    this.isAutomated = isAutomated;
    return this;
  }

   /**
   * Specifies a test point automation status to search for
   * @return isAutomated
  **/
  @javax.annotation.Nullable
  public Boolean getIsAutomated() {
    return isAutomated;
  }


  public void setIsAutomated(Boolean isAutomated) {
    this.isAutomated = isAutomated;
  }


  public ApiV2TestPointsSearchPostRequest name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Specifies a test point name to search for
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ApiV2TestPointsSearchPostRequest configurationIds(Set<UUID> configurationIds) {
    
    this.configurationIds = configurationIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addConfigurationIdsItem(UUID configurationIdsItem) {
    if (this.configurationIds == null) {
      this.configurationIds = new LinkedHashSet<>();
    }
    this.configurationIds.add(configurationIdsItem);
    return this;
  }

   /**
   * Specifies a test point configuration IDs to search for
   * @return configurationIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getConfigurationIds() {
    return configurationIds;
  }


  public void setConfigurationIds(Set<UUID> configurationIds) {
    this.configurationIds = configurationIds;
  }


  public ApiV2TestPointsSearchPostRequest testerIds(Set<UUID> testerIds) {
    
    this.testerIds = testerIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addTesterIdsItem(UUID testerIdsItem) {
    if (this.testerIds == null) {
      this.testerIds = new LinkedHashSet<>();
    }
    this.testerIds.add(testerIdsItem);
    return this;
  }

   /**
   * Specifies a test point assigned user IDs to search for
   * @return testerIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getTesterIds() {
    return testerIds;
  }


  public void setTesterIds(Set<UUID> testerIds) {
    this.testerIds = testerIds;
  }


  public ApiV2TestPointsSearchPostRequest duration(TestPointFilterModelDuration duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Get duration
   * @return duration
  **/
  @javax.annotation.Nullable
  public TestPointFilterModelDuration getDuration() {
    return duration;
  }


  public void setDuration(TestPointFilterModelDuration duration) {
    this.duration = duration;
  }


  public ApiV2TestPointsSearchPostRequest sectionIds(Set<UUID> sectionIds) {
    
    this.sectionIds = sectionIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addSectionIdsItem(UUID sectionIdsItem) {
    if (this.sectionIds == null) {
      this.sectionIds = new LinkedHashSet<>();
    }
    this.sectionIds.add(sectionIdsItem);
    return this;
  }

   /**
   * Specifies a test point work item section IDs to search for
   * @return sectionIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getSectionIds() {
    return sectionIds;
  }


  public void setSectionIds(Set<UUID> sectionIds) {
    this.sectionIds = sectionIds;
  }


  public ApiV2TestPointsSearchPostRequest createdDate(TestPointFilterModelCreatedDate createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @javax.annotation.Nullable
  public TestPointFilterModelCreatedDate getCreatedDate() {
    return createdDate;
  }


  public void setCreatedDate(TestPointFilterModelCreatedDate createdDate) {
    this.createdDate = createdDate;
  }


  public ApiV2TestPointsSearchPostRequest createdByIds(Set<UUID> createdByIds) {
    
    this.createdByIds = createdByIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addCreatedByIdsItem(UUID createdByIdsItem) {
    if (this.createdByIds == null) {
      this.createdByIds = new LinkedHashSet<>();
    }
    this.createdByIds.add(createdByIdsItem);
    return this;
  }

   /**
   * Specifies a test point creator IDs to search for
   * @return createdByIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getCreatedByIds() {
    return createdByIds;
  }


  public void setCreatedByIds(Set<UUID> createdByIds) {
    this.createdByIds = createdByIds;
  }


  public ApiV2TestPointsSearchPostRequest modifiedDate(TestPointFilterModelModifiedDate modifiedDate) {
    
    this.modifiedDate = modifiedDate;
    return this;
  }

   /**
   * Get modifiedDate
   * @return modifiedDate
  **/
  @javax.annotation.Nullable
  public TestPointFilterModelModifiedDate getModifiedDate() {
    return modifiedDate;
  }


  public void setModifiedDate(TestPointFilterModelModifiedDate modifiedDate) {
    this.modifiedDate = modifiedDate;
  }


  public ApiV2TestPointsSearchPostRequest modifiedByIds(Set<UUID> modifiedByIds) {
    
    this.modifiedByIds = modifiedByIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addModifiedByIdsItem(UUID modifiedByIdsItem) {
    if (this.modifiedByIds == null) {
      this.modifiedByIds = new LinkedHashSet<>();
    }
    this.modifiedByIds.add(modifiedByIdsItem);
    return this;
  }

   /**
   * Specifies a test point last editor IDs to search for
   * @return modifiedByIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getModifiedByIds() {
    return modifiedByIds;
  }


  public void setModifiedByIds(Set<UUID> modifiedByIds) {
    this.modifiedByIds = modifiedByIds;
  }


  public ApiV2TestPointsSearchPostRequest tags(Set<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new LinkedHashSet<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Specifies a test point tags to search for
   * @return tags
  **/
  @javax.annotation.Nullable
  public Set<String> getTags() {
    return tags;
  }


  public void setTags(Set<String> tags) {
    this.tags = tags;
  }


  public ApiV2TestPointsSearchPostRequest attributes(Map<String, Set<String>> attributes) {
    
    this.attributes = attributes;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest putAttributesItem(String key, Set<String> attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Specifies a test point attributes to search for
   * @return attributes
  **/
  @javax.annotation.Nullable
  public Map<String, Set<String>> getAttributes() {
    return attributes;
  }


  public void setAttributes(Map<String, Set<String>> attributes) {
    this.attributes = attributes;
  }


  public ApiV2TestPointsSearchPostRequest workItemCreatedDate(TestPointFilterModelWorkItemCreatedDate workItemCreatedDate) {
    
    this.workItemCreatedDate = workItemCreatedDate;
    return this;
  }

   /**
   * Get workItemCreatedDate
   * @return workItemCreatedDate
  **/
  @javax.annotation.Nullable
  public TestPointFilterModelWorkItemCreatedDate getWorkItemCreatedDate() {
    return workItemCreatedDate;
  }


  public void setWorkItemCreatedDate(TestPointFilterModelWorkItemCreatedDate workItemCreatedDate) {
    this.workItemCreatedDate = workItemCreatedDate;
  }


  public ApiV2TestPointsSearchPostRequest workItemCreatedByIds(Set<UUID> workItemCreatedByIds) {
    
    this.workItemCreatedByIds = workItemCreatedByIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addWorkItemCreatedByIdsItem(UUID workItemCreatedByIdsItem) {
    if (this.workItemCreatedByIds == null) {
      this.workItemCreatedByIds = new LinkedHashSet<>();
    }
    this.workItemCreatedByIds.add(workItemCreatedByIdsItem);
    return this;
  }

   /**
   * Specifies a work item creator IDs to search for
   * @return workItemCreatedByIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getWorkItemCreatedByIds() {
    return workItemCreatedByIds;
  }


  public void setWorkItemCreatedByIds(Set<UUID> workItemCreatedByIds) {
    this.workItemCreatedByIds = workItemCreatedByIds;
  }


  public ApiV2TestPointsSearchPostRequest workItemModifiedDate(TestPointFilterModelWorkItemModifiedDate workItemModifiedDate) {
    
    this.workItemModifiedDate = workItemModifiedDate;
    return this;
  }

   /**
   * Get workItemModifiedDate
   * @return workItemModifiedDate
  **/
  @javax.annotation.Nullable
  public TestPointFilterModelWorkItemModifiedDate getWorkItemModifiedDate() {
    return workItemModifiedDate;
  }


  public void setWorkItemModifiedDate(TestPointFilterModelWorkItemModifiedDate workItemModifiedDate) {
    this.workItemModifiedDate = workItemModifiedDate;
  }


  public ApiV2TestPointsSearchPostRequest workItemModifiedByIds(Set<UUID> workItemModifiedByIds) {
    
    this.workItemModifiedByIds = workItemModifiedByIds;
    return this;
  }

  public ApiV2TestPointsSearchPostRequest addWorkItemModifiedByIdsItem(UUID workItemModifiedByIdsItem) {
    if (this.workItemModifiedByIds == null) {
      this.workItemModifiedByIds = new LinkedHashSet<>();
    }
    this.workItemModifiedByIds.add(workItemModifiedByIdsItem);
    return this;
  }

   /**
   * Specifies a work item last editor IDs to search for
   * @return workItemModifiedByIds
  **/
  @javax.annotation.Nullable
  public Set<UUID> getWorkItemModifiedByIds() {
    return workItemModifiedByIds;
  }


  public void setWorkItemModifiedByIds(Set<UUID> workItemModifiedByIds) {
    this.workItemModifiedByIds = workItemModifiedByIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiV2TestPointsSearchPostRequest apiV2TestPointsSearchPostRequest = (ApiV2TestPointsSearchPostRequest) o;
    return Objects.equals(this.testPlanIds, apiV2TestPointsSearchPostRequest.testPlanIds) &&
        Objects.equals(this.testSuiteIds, apiV2TestPointsSearchPostRequest.testSuiteIds) &&
        Objects.equals(this.workItemGlobalIds, apiV2TestPointsSearchPostRequest.workItemGlobalIds) &&
        Objects.equals(this.statuses, apiV2TestPointsSearchPostRequest.statuses) &&
        Objects.equals(this.priorities, apiV2TestPointsSearchPostRequest.priorities) &&
        Objects.equals(this.isAutomated, apiV2TestPointsSearchPostRequest.isAutomated) &&
        Objects.equals(this.name, apiV2TestPointsSearchPostRequest.name) &&
        Objects.equals(this.configurationIds, apiV2TestPointsSearchPostRequest.configurationIds) &&
        Objects.equals(this.testerIds, apiV2TestPointsSearchPostRequest.testerIds) &&
        Objects.equals(this.duration, apiV2TestPointsSearchPostRequest.duration) &&
        Objects.equals(this.sectionIds, apiV2TestPointsSearchPostRequest.sectionIds) &&
        Objects.equals(this.createdDate, apiV2TestPointsSearchPostRequest.createdDate) &&
        Objects.equals(this.createdByIds, apiV2TestPointsSearchPostRequest.createdByIds) &&
        Objects.equals(this.modifiedDate, apiV2TestPointsSearchPostRequest.modifiedDate) &&
        Objects.equals(this.modifiedByIds, apiV2TestPointsSearchPostRequest.modifiedByIds) &&
        Objects.equals(this.tags, apiV2TestPointsSearchPostRequest.tags) &&
        Objects.equals(this.attributes, apiV2TestPointsSearchPostRequest.attributes) &&
        Objects.equals(this.workItemCreatedDate, apiV2TestPointsSearchPostRequest.workItemCreatedDate) &&
        Objects.equals(this.workItemCreatedByIds, apiV2TestPointsSearchPostRequest.workItemCreatedByIds) &&
        Objects.equals(this.workItemModifiedDate, apiV2TestPointsSearchPostRequest.workItemModifiedDate) &&
        Objects.equals(this.workItemModifiedByIds, apiV2TestPointsSearchPostRequest.workItemModifiedByIds);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(testPlanIds, testSuiteIds, workItemGlobalIds, statuses, priorities, isAutomated, name, configurationIds, testerIds, duration, sectionIds, createdDate, createdByIds, modifiedDate, modifiedByIds, tags, attributes, workItemCreatedDate, workItemCreatedByIds, workItemModifiedDate, workItemModifiedByIds);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiV2TestPointsSearchPostRequest {\n");
    sb.append("    testPlanIds: ").append(toIndentedString(testPlanIds)).append("\n");
    sb.append("    testSuiteIds: ").append(toIndentedString(testSuiteIds)).append("\n");
    sb.append("    workItemGlobalIds: ").append(toIndentedString(workItemGlobalIds)).append("\n");
    sb.append("    statuses: ").append(toIndentedString(statuses)).append("\n");
    sb.append("    priorities: ").append(toIndentedString(priorities)).append("\n");
    sb.append("    isAutomated: ").append(toIndentedString(isAutomated)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    configurationIds: ").append(toIndentedString(configurationIds)).append("\n");
    sb.append("    testerIds: ").append(toIndentedString(testerIds)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    sectionIds: ").append(toIndentedString(sectionIds)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    createdByIds: ").append(toIndentedString(createdByIds)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    modifiedByIds: ").append(toIndentedString(modifiedByIds)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    workItemCreatedDate: ").append(toIndentedString(workItemCreatedDate)).append("\n");
    sb.append("    workItemCreatedByIds: ").append(toIndentedString(workItemCreatedByIds)).append("\n");
    sb.append("    workItemModifiedDate: ").append(toIndentedString(workItemModifiedDate)).append("\n");
    sb.append("    workItemModifiedByIds: ").append(toIndentedString(workItemModifiedByIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("testPlanIds");
    openapiFields.add("testSuiteIds");
    openapiFields.add("workItemGlobalIds");
    openapiFields.add("statuses");
    openapiFields.add("priorities");
    openapiFields.add("isAutomated");
    openapiFields.add("name");
    openapiFields.add("configurationIds");
    openapiFields.add("testerIds");
    openapiFields.add("duration");
    openapiFields.add("sectionIds");
    openapiFields.add("createdDate");
    openapiFields.add("createdByIds");
    openapiFields.add("modifiedDate");
    openapiFields.add("modifiedByIds");
    openapiFields.add("tags");
    openapiFields.add("attributes");
    openapiFields.add("workItemCreatedDate");
    openapiFields.add("workItemCreatedByIds");
    openapiFields.add("workItemModifiedDate");
    openapiFields.add("workItemModifiedByIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ApiV2TestPointsSearchPostRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ApiV2TestPointsSearchPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ApiV2TestPointsSearchPostRequest is not found in the empty JSON string", ApiV2TestPointsSearchPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ApiV2TestPointsSearchPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ApiV2TestPointsSearchPostRequest` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("testPlanIds") != null && !jsonObj.get("testPlanIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `testPlanIds` to be an array in the JSON string but got `%s`", jsonObj.get("testPlanIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("testSuiteIds") != null && !jsonObj.get("testSuiteIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `testSuiteIds` to be an array in the JSON string but got `%s`", jsonObj.get("testSuiteIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("workItemGlobalIds") != null && !jsonObj.get("workItemGlobalIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `workItemGlobalIds` to be an array in the JSON string but got `%s`", jsonObj.get("workItemGlobalIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("statuses") != null && !jsonObj.get("statuses").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `statuses` to be an array in the JSON string but got `%s`", jsonObj.get("statuses").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("priorities") != null && !jsonObj.get("priorities").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `priorities` to be an array in the JSON string but got `%s`", jsonObj.get("priorities").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("configurationIds") != null && !jsonObj.get("configurationIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `configurationIds` to be an array in the JSON string but got `%s`", jsonObj.get("configurationIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("testerIds") != null && !jsonObj.get("testerIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `testerIds` to be an array in the JSON string but got `%s`", jsonObj.get("testerIds").toString()));
      }
      // validate the optional field `duration`
      if (jsonObj.get("duration") != null && !jsonObj.get("duration").isJsonNull()) {
        TestPointFilterModelDuration.validateJsonObject(jsonObj.getAsJsonObject("duration"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("sectionIds") != null && !jsonObj.get("sectionIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `sectionIds` to be an array in the JSON string but got `%s`", jsonObj.get("sectionIds").toString()));
      }
      // validate the optional field `createdDate`
      if (jsonObj.get("createdDate") != null && !jsonObj.get("createdDate").isJsonNull()) {
        TestPointFilterModelCreatedDate.validateJsonObject(jsonObj.getAsJsonObject("createdDate"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("createdByIds") != null && !jsonObj.get("createdByIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `createdByIds` to be an array in the JSON string but got `%s`", jsonObj.get("createdByIds").toString()));
      }
      // validate the optional field `modifiedDate`
      if (jsonObj.get("modifiedDate") != null && !jsonObj.get("modifiedDate").isJsonNull()) {
        TestPointFilterModelModifiedDate.validateJsonObject(jsonObj.getAsJsonObject("modifiedDate"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("modifiedByIds") != null && !jsonObj.get("modifiedByIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `modifiedByIds` to be an array in the JSON string but got `%s`", jsonObj.get("modifiedByIds").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
      // validate the optional field `workItemCreatedDate`
      if (jsonObj.get("workItemCreatedDate") != null && !jsonObj.get("workItemCreatedDate").isJsonNull()) {
        TestPointFilterModelWorkItemCreatedDate.validateJsonObject(jsonObj.getAsJsonObject("workItemCreatedDate"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("workItemCreatedByIds") != null && !jsonObj.get("workItemCreatedByIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `workItemCreatedByIds` to be an array in the JSON string but got `%s`", jsonObj.get("workItemCreatedByIds").toString()));
      }
      // validate the optional field `workItemModifiedDate`
      if (jsonObj.get("workItemModifiedDate") != null && !jsonObj.get("workItemModifiedDate").isJsonNull()) {
        TestPointFilterModelWorkItemModifiedDate.validateJsonObject(jsonObj.getAsJsonObject("workItemModifiedDate"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("workItemModifiedByIds") != null && !jsonObj.get("workItemModifiedByIds").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `workItemModifiedByIds` to be an array in the JSON string but got `%s`", jsonObj.get("workItemModifiedByIds").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiV2TestPointsSearchPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiV2TestPointsSearchPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiV2TestPointsSearchPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiV2TestPointsSearchPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiV2TestPointsSearchPostRequest>() {
           @Override
           public void write(JsonWriter out, ApiV2TestPointsSearchPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiV2TestPointsSearchPostRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ApiV2TestPointsSearchPostRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ApiV2TestPointsSearchPostRequest
  * @throws IOException if the JSON string is invalid with respect to ApiV2TestPointsSearchPostRequest
  */
  public static ApiV2TestPointsSearchPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiV2TestPointsSearchPostRequest.class);
  }

 /**
  * Convert an instance of ApiV2TestPointsSearchPostRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

