/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.client.model.RequestTypeModel;
import ru.testit.client.model.WebHookEventTypeModel;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.client.invoker.JSON;


/**
 * ApiV2WebhooksPostRequest
 */
@JsonPropertyOrder({
  ApiV2WebhooksPostRequest.JSON_PROPERTY_PROJECT_ID,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_EVENT_TYPE,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_DESCRIPTION,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_URL,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_REQUEST_TYPE,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_SHOULD_SEND_BODY,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_HEADERS,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_QUERY_PARAMETERS,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_IS_ENABLED,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_SHOULD_SEND_CUSTOM_BODY,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_CUSTOM_BODY,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_SHOULD_REPLACE_PARAMETERS,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_SHOULD_ESCAPE_PARAMETERS,
  ApiV2WebhooksPostRequest.JSON_PROPERTY_NAME
})
@JsonTypeName("_api_v2_webhooks_post_request")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ApiV2WebhooksPostRequest {
  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  private UUID projectId;

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  private WebHookEventTypeModel eventType;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public static final String JSON_PROPERTY_REQUEST_TYPE = "requestType";
  private RequestTypeModel requestType;

  public static final String JSON_PROPERTY_SHOULD_SEND_BODY = "shouldSendBody";
  private Boolean shouldSendBody;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  private JsonNullable<Map<String, String>> headers = JsonNullable.<Map<String, String>>undefined();

  public static final String JSON_PROPERTY_QUERY_PARAMETERS = "queryParameters";
  private JsonNullable<Map<String, String>> queryParameters = JsonNullable.<Map<String, String>>undefined();

  public static final String JSON_PROPERTY_IS_ENABLED = "isEnabled";
  private Boolean isEnabled;

  public static final String JSON_PROPERTY_SHOULD_SEND_CUSTOM_BODY = "shouldSendCustomBody";
  private Boolean shouldSendCustomBody;

  public static final String JSON_PROPERTY_CUSTOM_BODY = "customBody";
  private JsonNullable<String> customBody = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SHOULD_REPLACE_PARAMETERS = "shouldReplaceParameters";
  private Boolean shouldReplaceParameters;

  public static final String JSON_PROPERTY_SHOULD_ESCAPE_PARAMETERS = "shouldEscapeParameters";
  private Boolean shouldEscapeParameters;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public ApiV2WebhooksPostRequest() { 
  }

  public ApiV2WebhooksPostRequest projectId(UUID projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Unique ID of the webhook project
   * @return projectId
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(UUID projectId) {
    this.projectId = projectId;
  }


  public ApiV2WebhooksPostRequest eventType(WebHookEventTypeModel eventType) {
    this.eventType = eventType;
    return this;
  }

   /**
   * Get eventType
   * @return eventType
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public WebHookEventTypeModel getEventType() {
    return eventType;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEventType(WebHookEventTypeModel eventType) {
    this.eventType = eventType;
  }


  public ApiV2WebhooksPostRequest description(String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

   /**
   * Description of the webhook
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public ApiV2WebhooksPostRequest url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Request URL of the webhook
   * @return url
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(String url) {
    this.url = url;
  }


  public ApiV2WebhooksPostRequest requestType(RequestTypeModel requestType) {
    this.requestType = requestType;
    return this;
  }

   /**
   * Get requestType
   * @return requestType
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REQUEST_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RequestTypeModel getRequestType() {
    return requestType;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestType(RequestTypeModel requestType) {
    this.requestType = requestType;
  }


  public ApiV2WebhooksPostRequest shouldSendBody(Boolean shouldSendBody) {
    this.shouldSendBody = shouldSendBody;
    return this;
  }

   /**
   * Indicates if the webhook sends body
   * @return shouldSendBody
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOULD_SEND_BODY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getShouldSendBody() {
    return shouldSendBody;
  }


  @JsonProperty(JSON_PROPERTY_SHOULD_SEND_BODY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShouldSendBody(Boolean shouldSendBody) {
    this.shouldSendBody = shouldSendBody;
  }


  public ApiV2WebhooksPostRequest headers(Map<String, String> headers) {
    this.headers = JsonNullable.<Map<String, String>>of(headers);
    return this;
  }

  public ApiV2WebhooksPostRequest putHeadersItem(String key, String headersItem) {
    if (this.headers == null || !this.headers.isPresent()) {
      this.headers = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.headers.get().put(key, headersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * Collection of the webhook headers
   * @return headers
  **/
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, String> getHeaders() {
        return headers.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HEADERS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getHeaders_JsonNullable() {
    return headers;
  }
  
  @JsonProperty(JSON_PROPERTY_HEADERS)
  public void setHeaders_JsonNullable(JsonNullable<Map<String, String>> headers) {
    this.headers = headers;
  }

  public void setHeaders(Map<String, String> headers) {
    this.headers = JsonNullable.<Map<String, String>>of(headers);
  }


  public ApiV2WebhooksPostRequest queryParameters(Map<String, String> queryParameters) {
    this.queryParameters = JsonNullable.<Map<String, String>>of(queryParameters);
    return this;
  }

  public ApiV2WebhooksPostRequest putQueryParametersItem(String key, String queryParametersItem) {
    if (this.queryParameters == null || !this.queryParameters.isPresent()) {
      this.queryParameters = JsonNullable.<Map<String, String>>of(new HashMap<>());
    }
    try {
      this.queryParameters.get().put(key, queryParametersItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

   /**
   * Collection of the webhook query parameters
   * @return queryParameters
  **/
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Map<String, String> getQueryParameters() {
        return queryParameters.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_QUERY_PARAMETERS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Map<String, String>> getQueryParameters_JsonNullable() {
    return queryParameters;
  }
  
  @JsonProperty(JSON_PROPERTY_QUERY_PARAMETERS)
  public void setQueryParameters_JsonNullable(JsonNullable<Map<String, String>> queryParameters) {
    this.queryParameters = queryParameters;
  }

  public void setQueryParameters(Map<String, String> queryParameters) {
    this.queryParameters = JsonNullable.<Map<String, String>>of(queryParameters);
  }


  public ApiV2WebhooksPostRequest isEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

   /**
   * Indicates if the webhook is active
   * @return isEnabled
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsEnabled() {
    return isEnabled;
  }


  @JsonProperty(JSON_PROPERTY_IS_ENABLED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsEnabled(Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }


  public ApiV2WebhooksPostRequest shouldSendCustomBody(Boolean shouldSendCustomBody) {
    this.shouldSendCustomBody = shouldSendCustomBody;
    return this;
  }

   /**
   * Indicates if the webhook sends custom body
   * @return shouldSendCustomBody
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOULD_SEND_CUSTOM_BODY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getShouldSendCustomBody() {
    return shouldSendCustomBody;
  }


  @JsonProperty(JSON_PROPERTY_SHOULD_SEND_CUSTOM_BODY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShouldSendCustomBody(Boolean shouldSendCustomBody) {
    this.shouldSendCustomBody = shouldSendCustomBody;
  }


  public ApiV2WebhooksPostRequest customBody(String customBody) {
    this.customBody = JsonNullable.<String>of(customBody);
    return this;
  }

   /**
   * Custom body of the webhook
   * @return customBody
  **/
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getCustomBody() {
        return customBody.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CUSTOM_BODY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCustomBody_JsonNullable() {
    return customBody;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOM_BODY)
  public void setCustomBody_JsonNullable(JsonNullable<String> customBody) {
    this.customBody = customBody;
  }

  public void setCustomBody(String customBody) {
    this.customBody = JsonNullable.<String>of(customBody);
  }


  public ApiV2WebhooksPostRequest shouldReplaceParameters(Boolean shouldReplaceParameters) {
    this.shouldReplaceParameters = shouldReplaceParameters;
    return this;
  }

   /**
   * Indicates if the webhook injects parameters
   * @return shouldReplaceParameters
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOULD_REPLACE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getShouldReplaceParameters() {
    return shouldReplaceParameters;
  }


  @JsonProperty(JSON_PROPERTY_SHOULD_REPLACE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShouldReplaceParameters(Boolean shouldReplaceParameters) {
    this.shouldReplaceParameters = shouldReplaceParameters;
  }


  public ApiV2WebhooksPostRequest shouldEscapeParameters(Boolean shouldEscapeParameters) {
    this.shouldEscapeParameters = shouldEscapeParameters;
    return this;
  }

   /**
   * Indicates if the webhook escapes invalid characters in parameters
   * @return shouldEscapeParameters
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHOULD_ESCAPE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getShouldEscapeParameters() {
    return shouldEscapeParameters;
  }


  @JsonProperty(JSON_PROPERTY_SHOULD_ESCAPE_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShouldEscapeParameters(Boolean shouldEscapeParameters) {
    this.shouldEscapeParameters = shouldEscapeParameters;
  }


  public ApiV2WebhooksPostRequest name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the webhook
   * @return name
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  /**
   * Return true if this _api_v2_webhooks_post_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiV2WebhooksPostRequest apiV2WebhooksPostRequest = (ApiV2WebhooksPostRequest) o;
    return Objects.equals(this.projectId, apiV2WebhooksPostRequest.projectId) &&
        Objects.equals(this.eventType, apiV2WebhooksPostRequest.eventType) &&
        equalsNullable(this.description, apiV2WebhooksPostRequest.description) &&
        Objects.equals(this.url, apiV2WebhooksPostRequest.url) &&
        Objects.equals(this.requestType, apiV2WebhooksPostRequest.requestType) &&
        Objects.equals(this.shouldSendBody, apiV2WebhooksPostRequest.shouldSendBody) &&
        equalsNullable(this.headers, apiV2WebhooksPostRequest.headers) &&
        equalsNullable(this.queryParameters, apiV2WebhooksPostRequest.queryParameters) &&
        Objects.equals(this.isEnabled, apiV2WebhooksPostRequest.isEnabled) &&
        Objects.equals(this.shouldSendCustomBody, apiV2WebhooksPostRequest.shouldSendCustomBody) &&
        equalsNullable(this.customBody, apiV2WebhooksPostRequest.customBody) &&
        Objects.equals(this.shouldReplaceParameters, apiV2WebhooksPostRequest.shouldReplaceParameters) &&
        Objects.equals(this.shouldEscapeParameters, apiV2WebhooksPostRequest.shouldEscapeParameters) &&
        Objects.equals(this.name, apiV2WebhooksPostRequest.name);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectId, eventType, hashCodeNullable(description), url, requestType, shouldSendBody, hashCodeNullable(headers), hashCodeNullable(queryParameters), isEnabled, shouldSendCustomBody, hashCodeNullable(customBody), shouldReplaceParameters, shouldEscapeParameters, name);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiV2WebhooksPostRequest {\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    requestType: ").append(toIndentedString(requestType)).append("\n");
    sb.append("    shouldSendBody: ").append(toIndentedString(shouldSendBody)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    queryParameters: ").append(toIndentedString(queryParameters)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    shouldSendCustomBody: ").append(toIndentedString(shouldSendCustomBody)).append("\n");
    sb.append("    customBody: ").append(toIndentedString(customBody)).append("\n");
    sb.append("    shouldReplaceParameters: ").append(toIndentedString(shouldReplaceParameters)).append("\n");
    sb.append("    shouldEscapeParameters: ").append(toIndentedString(shouldEscapeParameters)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

