/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import ru.testit.client.model.AutotestSelectModelExtractionModel;
import ru.testit.client.model.AutotestSelectModelFilter;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import ru.testit.client.invoker.JSON;

/**
 * FlakyBulkModelAutotestSelect
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FlakyBulkModelAutotestSelect {
  public static final String SERIALIZED_NAME_FILTER = "filter";
  @SerializedName(SERIALIZED_NAME_FILTER)
  private AutotestSelectModelFilter filter;

  public static final String SERIALIZED_NAME_EXTRACTION_MODEL = "extractionModel";
  @SerializedName(SERIALIZED_NAME_EXTRACTION_MODEL)
  private AutotestSelectModelExtractionModel extractionModel;

  public FlakyBulkModelAutotestSelect() {
  }

  public FlakyBulkModelAutotestSelect filter(AutotestSelectModelFilter filter) {
    
    this.filter = filter;
    return this;
  }

   /**
   * Get filter
   * @return filter
  **/
  @javax.annotation.Nonnull
  public AutotestSelectModelFilter getFilter() {
    return filter;
  }


  public void setFilter(AutotestSelectModelFilter filter) {
    this.filter = filter;
  }


  public FlakyBulkModelAutotestSelect extractionModel(AutotestSelectModelExtractionModel extractionModel) {
    
    this.extractionModel = extractionModel;
    return this;
  }

   /**
   * Get extractionModel
   * @return extractionModel
  **/
  @javax.annotation.Nonnull
  public AutotestSelectModelExtractionModel getExtractionModel() {
    return extractionModel;
  }


  public void setExtractionModel(AutotestSelectModelExtractionModel extractionModel) {
    this.extractionModel = extractionModel;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlakyBulkModelAutotestSelect flakyBulkModelAutotestSelect = (FlakyBulkModelAutotestSelect) o;
    return Objects.equals(this.filter, flakyBulkModelAutotestSelect.filter) &&
        Objects.equals(this.extractionModel, flakyBulkModelAutotestSelect.extractionModel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filter, extractionModel);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlakyBulkModelAutotestSelect {\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    extractionModel: ").append(toIndentedString(extractionModel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("filter");
    openapiFields.add("extractionModel");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("filter");
    openapiRequiredFields.add("extractionModel");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FlakyBulkModelAutotestSelect
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FlakyBulkModelAutotestSelect.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FlakyBulkModelAutotestSelect is not found in the empty JSON string", FlakyBulkModelAutotestSelect.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!FlakyBulkModelAutotestSelect.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FlakyBulkModelAutotestSelect` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FlakyBulkModelAutotestSelect.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `filter`
      AutotestSelectModelFilter.validateJsonObject(jsonObj.getAsJsonObject("filter"));
      // validate the required field `extractionModel`
      AutotestSelectModelExtractionModel.validateJsonObject(jsonObj.getAsJsonObject("extractionModel"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FlakyBulkModelAutotestSelect.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FlakyBulkModelAutotestSelect' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FlakyBulkModelAutotestSelect> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FlakyBulkModelAutotestSelect.class));

       return (TypeAdapter<T>) new TypeAdapter<FlakyBulkModelAutotestSelect>() {
           @Override
           public void write(JsonWriter out, FlakyBulkModelAutotestSelect value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FlakyBulkModelAutotestSelect read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FlakyBulkModelAutotestSelect given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FlakyBulkModelAutotestSelect
  * @throws IOException if the JSON string is invalid with respect to FlakyBulkModelAutotestSelect
  */
  public static FlakyBulkModelAutotestSelect fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FlakyBulkModelAutotestSelect.class);
  }

 /**
  * Convert an instance of FlakyBulkModelAutotestSelect to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

