/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import ru.testit.client.model.ExternalFormModel;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.client.invoker.JSON;


/**
 * GetExternalFormApiResult
 */
@JsonPropertyOrder({
  GetExternalFormApiResult.JSON_PROPERTY_TEST_RESULT_IDS,
  GetExternalFormApiResult.JSON_PROPERTY_FORM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class GetExternalFormApiResult {
  public static final String JSON_PROPERTY_TEST_RESULT_IDS = "testResultIds";
  private List<UUID> testResultIds = new ArrayList<>();

  public static final String JSON_PROPERTY_FORM = "form";
  private ExternalFormModel form;

  public GetExternalFormApiResult() { 
  }

  public GetExternalFormApiResult testResultIds(List<UUID> testResultIds) {
    this.testResultIds = testResultIds;
    return this;
  }

  public GetExternalFormApiResult addTestResultIdsItem(UUID testResultIdsItem) {
    if (this.testResultIds == null) {
      this.testResultIds = new ArrayList<>();
    }
    this.testResultIds.add(testResultIdsItem);
    return this;
  }

  /**
   * Linked test result IDs
   * @return testResultIds
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TEST_RESULT_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<UUID> getTestResultIds() {
    return testResultIds;
  }


  @JsonProperty(JSON_PROPERTY_TEST_RESULT_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTestResultIds(List<UUID> testResultIds) {
    this.testResultIds = testResultIds;
  }


  public GetExternalFormApiResult form(ExternalFormModel form) {
    this.form = form;
    return this;
  }

  /**
   * External form definition
   * @return form
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ExternalFormModel getForm() {
    return form;
  }


  @JsonProperty(JSON_PROPERTY_FORM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setForm(ExternalFormModel form) {
    this.form = form;
  }


  /**
   * Return true if this GetExternalFormApiResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetExternalFormApiResult getExternalFormApiResult = (GetExternalFormApiResult) o;
    return Objects.equals(this.testResultIds, getExternalFormApiResult.testResultIds) &&
        Objects.equals(this.form, getExternalFormApiResult.form);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testResultIds, form);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetExternalFormApiResult {\n");
    sb.append("    testResultIds: ").append(toIndentedString(testResultIds)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

