/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.client.invoker.JSON;


/**
 * StringChangedFieldWithDiffsViewModel
 */
@JsonPropertyOrder({
  StringChangedFieldWithDiffsViewModel.JSON_PROPERTY_DIFF_VALUE,
  StringChangedFieldWithDiffsViewModel.JSON_PROPERTY_OLD_VALUE,
  StringChangedFieldWithDiffsViewModel.JSON_PROPERTY_NEW_VALUE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.9.0")
public class StringChangedFieldWithDiffsViewModel {
  public static final String JSON_PROPERTY_DIFF_VALUE = "diffValue";
  private JsonNullable<String> diffValue = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OLD_VALUE = "oldValue";
  private JsonNullable<String> oldValue = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NEW_VALUE = "newValue";
  private JsonNullable<String> newValue = JsonNullable.<String>undefined();

  public StringChangedFieldWithDiffsViewModel() { 
  }

  public StringChangedFieldWithDiffsViewModel diffValue(String diffValue) {
    this.diffValue = JsonNullable.<String>of(diffValue);
    return this;
  }

  /**
   * Get diffValue
   * @return diffValue
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDiffValue() {
        return diffValue.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DIFF_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDiffValue_JsonNullable() {
    return diffValue;
  }
  
  @JsonProperty(JSON_PROPERTY_DIFF_VALUE)
  public void setDiffValue_JsonNullable(JsonNullable<String> diffValue) {
    this.diffValue = diffValue;
  }

  public void setDiffValue(String diffValue) {
    this.diffValue = JsonNullable.<String>of(diffValue);
  }


  public StringChangedFieldWithDiffsViewModel oldValue(String oldValue) {
    this.oldValue = JsonNullable.<String>of(oldValue);
    return this;
  }

  /**
   * Get oldValue
   * @return oldValue
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getOldValue() {
        return oldValue.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OLD_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOldValue_JsonNullable() {
    return oldValue;
  }
  
  @JsonProperty(JSON_PROPERTY_OLD_VALUE)
  public void setOldValue_JsonNullable(JsonNullable<String> oldValue) {
    this.oldValue = oldValue;
  }

  public void setOldValue(String oldValue) {
    this.oldValue = JsonNullable.<String>of(oldValue);
  }


  public StringChangedFieldWithDiffsViewModel newValue(String newValue) {
    this.newValue = JsonNullable.<String>of(newValue);
    return this;
  }

  /**
   * Get newValue
   * @return newValue
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getNewValue() {
        return newValue.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEW_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getNewValue_JsonNullable() {
    return newValue;
  }
  
  @JsonProperty(JSON_PROPERTY_NEW_VALUE)
  public void setNewValue_JsonNullable(JsonNullable<String> newValue) {
    this.newValue = newValue;
  }

  public void setNewValue(String newValue) {
    this.newValue = JsonNullable.<String>of(newValue);
  }


  /**
   * Return true if this StringChangedFieldWithDiffsViewModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StringChangedFieldWithDiffsViewModel stringChangedFieldWithDiffsViewModel = (StringChangedFieldWithDiffsViewModel) o;
    return equalsNullable(this.diffValue, stringChangedFieldWithDiffsViewModel.diffValue) &&
        equalsNullable(this.oldValue, stringChangedFieldWithDiffsViewModel.oldValue) &&
        equalsNullable(this.newValue, stringChangedFieldWithDiffsViewModel.newValue);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(diffValue), hashCodeNullable(oldValue), hashCodeNullable(newValue));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StringChangedFieldWithDiffsViewModel {\n");
    sb.append("    diffValue: ").append(toIndentedString(diffValue)).append("\n");
    sb.append("    oldValue: ").append(toIndentedString(oldValue)).append("\n");
    sb.append("    newValue: ").append(toIndentedString(newValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

