/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.testit.client.model.TagModel;
import ru.testit.client.model.TestPlanStatusModel;
import ru.testit.client.model.TestPointAnalyticResult;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.client.invoker.JSON;


/**
 * TestPlanWithAnalyticModel
 */
@JsonPropertyOrder({
  TestPlanWithAnalyticModel.JSON_PROPERTY_ANALYTIC,
  TestPlanWithAnalyticModel.JSON_PROPERTY_STATUS,
  TestPlanWithAnalyticModel.JSON_PROPERTY_CREATED_BY_ID,
  TestPlanWithAnalyticModel.JSON_PROPERTY_GLOBAL_ID,
  TestPlanWithAnalyticModel.JSON_PROPERTY_IS_DELETED,
  TestPlanWithAnalyticModel.JSON_PROPERTY_ID,
  TestPlanWithAnalyticModel.JSON_PROPERTY_NAME,
  TestPlanWithAnalyticModel.JSON_PROPERTY_PROJECT_ID,
  TestPlanWithAnalyticModel.JSON_PROPERTY_ATTRIBUTES,
  TestPlanWithAnalyticModel.JSON_PROPERTY_STARTED_ON,
  TestPlanWithAnalyticModel.JSON_PROPERTY_COMPLETED_ON,
  TestPlanWithAnalyticModel.JSON_PROPERTY_CREATED_DATE,
  TestPlanWithAnalyticModel.JSON_PROPERTY_MODIFIED_DATE,
  TestPlanWithAnalyticModel.JSON_PROPERTY_MODIFIED_BY_ID,
  TestPlanWithAnalyticModel.JSON_PROPERTY_LOCKED_DATE,
  TestPlanWithAnalyticModel.JSON_PROPERTY_LOCKED_BY_ID,
  TestPlanWithAnalyticModel.JSON_PROPERTY_TAGS,
  TestPlanWithAnalyticModel.JSON_PROPERTY_START_DATE,
  TestPlanWithAnalyticModel.JSON_PROPERTY_END_DATE,
  TestPlanWithAnalyticModel.JSON_PROPERTY_DESCRIPTION,
  TestPlanWithAnalyticModel.JSON_PROPERTY_BUILD,
  TestPlanWithAnalyticModel.JSON_PROPERTY_PRODUCT_NAME,
  TestPlanWithAnalyticModel.JSON_PROPERTY_HAS_AUTOMATIC_DURATION_TIMER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
public class TestPlanWithAnalyticModel {
  public static final String JSON_PROPERTY_ANALYTIC = "analytic";
  @jakarta.annotation.Nonnull
  private TestPointAnalyticResult analytic;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private TestPlanStatusModel status;

  public static final String JSON_PROPERTY_CREATED_BY_ID = "createdById";
  @jakarta.annotation.Nonnull
  private UUID createdById;

  public static final String JSON_PROPERTY_GLOBAL_ID = "globalId";
  @jakarta.annotation.Nonnull
  private Long globalId;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nonnull
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_PROJECT_ID = "projectId";
  @jakarta.annotation.Nonnull
  private UUID projectId;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  @jakarta.annotation.Nonnull
  private Map<String, Object> attributes = new HashMap<>();

  public static final String JSON_PROPERTY_STARTED_ON = "startedOn";
  private JsonNullable<OffsetDateTime> startedOn = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_COMPLETED_ON = "completedOn";
  private JsonNullable<OffsetDateTime> completedOn = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_CREATED_DATE = "createdDate";
  private JsonNullable<OffsetDateTime> createdDate = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_MODIFIED_DATE = "modifiedDate";
  private JsonNullable<OffsetDateTime> modifiedDate = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_MODIFIED_BY_ID = "modifiedById";
  private JsonNullable<UUID> modifiedById = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_LOCKED_DATE = "lockedDate";
  private JsonNullable<OffsetDateTime> lockedDate = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_LOCKED_BY_ID = "lockedById";
  private JsonNullable<UUID> lockedById = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<List<TagModel>> tags = JsonNullable.<List<TagModel>>undefined();

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  private JsonNullable<OffsetDateTime> startDate = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  private JsonNullable<OffsetDateTime> endDate = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BUILD = "build";
  private JsonNullable<String> build = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PRODUCT_NAME = "productName";
  private JsonNullable<String> productName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_HAS_AUTOMATIC_DURATION_TIMER = "hasAutomaticDurationTimer";
  private JsonNullable<Boolean> hasAutomaticDurationTimer = JsonNullable.<Boolean>undefined();

  public TestPlanWithAnalyticModel() { 
  }

  public TestPlanWithAnalyticModel analytic(@jakarta.annotation.Nonnull TestPointAnalyticResult analytic) {
    this.analytic = analytic;
    return this;
  }

  /**
   * Get analytic
   * @return analytic
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ANALYTIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TestPointAnalyticResult getAnalytic() {
    return analytic;
  }


  @JsonProperty(JSON_PROPERTY_ANALYTIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAnalytic(@jakarta.annotation.Nonnull TestPointAnalyticResult analytic) {
    this.analytic = analytic;
  }


  public TestPlanWithAnalyticModel status(@jakarta.annotation.Nonnull TestPlanStatusModel status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TestPlanStatusModel getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull TestPlanStatusModel status) {
    this.status = status;
  }


  public TestPlanWithAnalyticModel createdById(@jakarta.annotation.Nonnull UUID createdById) {
    this.createdById = createdById;
    return this;
  }

  /**
   * Get createdById
   * @return createdById
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_BY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getCreatedById() {
    return createdById;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedById(@jakarta.annotation.Nonnull UUID createdById) {
    this.createdById = createdById;
  }


  public TestPlanWithAnalyticModel globalId(@jakarta.annotation.Nonnull Long globalId) {
    this.globalId = globalId;
    return this;
  }

  /**
   * Used for search Test plan
   * @return globalId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GLOBAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getGlobalId() {
    return globalId;
  }


  @JsonProperty(JSON_PROPERTY_GLOBAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGlobalId(@jakarta.annotation.Nonnull Long globalId) {
    this.globalId = globalId;
  }


  public TestPlanWithAnalyticModel isDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsDeleted(@jakarta.annotation.Nonnull Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public TestPlanWithAnalyticModel id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public TestPlanWithAnalyticModel name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public TestPlanWithAnalyticModel projectId(@jakarta.annotation.Nonnull UUID projectId) {
    this.projectId = projectId;
    return this;
  }

  /**
   * Get projectId
   * @return projectId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectId(@jakarta.annotation.Nonnull UUID projectId) {
    this.projectId = projectId;
  }


  public TestPlanWithAnalyticModel attributes(@jakarta.annotation.Nonnull Map<String, Object> attributes) {
    this.attributes = attributes;
    return this;
  }

  public TestPlanWithAnalyticModel putAttributesItem(String key, Object attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

  /**
   * Get attributes
   * @return attributes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)

  public Map<String, Object> getAttributes() {
    return attributes;
  }


  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setAttributes(@jakarta.annotation.Nonnull Map<String, Object> attributes) {
    this.attributes = attributes;
  }


  public TestPlanWithAnalyticModel startedOn(@jakarta.annotation.Nullable OffsetDateTime startedOn) {
    this.startedOn = JsonNullable.<OffsetDateTime>of(startedOn);
    return this;
  }

  /**
   * Set when test plan is starter (status changed to: In Progress)
   * @return startedOn
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getStartedOn() {
        return startedOn.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STARTED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getStartedOn_JsonNullable() {
    return startedOn;
  }
  
  @JsonProperty(JSON_PROPERTY_STARTED_ON)
  public void setStartedOn_JsonNullable(JsonNullable<OffsetDateTime> startedOn) {
    this.startedOn = startedOn;
  }

  public void setStartedOn(@jakarta.annotation.Nullable OffsetDateTime startedOn) {
    this.startedOn = JsonNullable.<OffsetDateTime>of(startedOn);
  }


  public TestPlanWithAnalyticModel completedOn(@jakarta.annotation.Nullable OffsetDateTime completedOn) {
    this.completedOn = JsonNullable.<OffsetDateTime>of(completedOn);
    return this;
  }

  /**
   * set when test plan status is completed (status changed to: Completed)
   * @return completedOn
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getCompletedOn() {
        return completedOn.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPLETED_ON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCompletedOn_JsonNullable() {
    return completedOn;
  }
  
  @JsonProperty(JSON_PROPERTY_COMPLETED_ON)
  public void setCompletedOn_JsonNullable(JsonNullable<OffsetDateTime> completedOn) {
    this.completedOn = completedOn;
  }

  public void setCompletedOn(@jakarta.annotation.Nullable OffsetDateTime completedOn) {
    this.completedOn = JsonNullable.<OffsetDateTime>of(completedOn);
  }


  public TestPlanWithAnalyticModel createdDate(@jakarta.annotation.Nullable OffsetDateTime createdDate) {
    this.createdDate = JsonNullable.<OffsetDateTime>of(createdDate);
    return this;
  }

  /**
   * Get createdDate
   * @return createdDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getCreatedDate() {
        return createdDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getCreatedDate_JsonNullable() {
    return createdDate;
  }
  
  @JsonProperty(JSON_PROPERTY_CREATED_DATE)
  public void setCreatedDate_JsonNullable(JsonNullable<OffsetDateTime> createdDate) {
    this.createdDate = createdDate;
  }

  public void setCreatedDate(@jakarta.annotation.Nullable OffsetDateTime createdDate) {
    this.createdDate = JsonNullable.<OffsetDateTime>of(createdDate);
  }


  public TestPlanWithAnalyticModel modifiedDate(@jakarta.annotation.Nullable OffsetDateTime modifiedDate) {
    this.modifiedDate = JsonNullable.<OffsetDateTime>of(modifiedDate);
    return this;
  }

  /**
   * Get modifiedDate
   * @return modifiedDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getModifiedDate() {
        return modifiedDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MODIFIED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getModifiedDate_JsonNullable() {
    return modifiedDate;
  }
  
  @JsonProperty(JSON_PROPERTY_MODIFIED_DATE)
  public void setModifiedDate_JsonNullable(JsonNullable<OffsetDateTime> modifiedDate) {
    this.modifiedDate = modifiedDate;
  }

  public void setModifiedDate(@jakarta.annotation.Nullable OffsetDateTime modifiedDate) {
    this.modifiedDate = JsonNullable.<OffsetDateTime>of(modifiedDate);
  }


  public TestPlanWithAnalyticModel modifiedById(@jakarta.annotation.Nullable UUID modifiedById) {
    this.modifiedById = JsonNullable.<UUID>of(modifiedById);
    return this;
  }

  /**
   * Get modifiedById
   * @return modifiedById
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public UUID getModifiedById() {
        return modifiedById.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MODIFIED_BY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getModifiedById_JsonNullable() {
    return modifiedById;
  }
  
  @JsonProperty(JSON_PROPERTY_MODIFIED_BY_ID)
  public void setModifiedById_JsonNullable(JsonNullable<UUID> modifiedById) {
    this.modifiedById = modifiedById;
  }

  public void setModifiedById(@jakarta.annotation.Nullable UUID modifiedById) {
    this.modifiedById = JsonNullable.<UUID>of(modifiedById);
  }


  public TestPlanWithAnalyticModel lockedDate(@jakarta.annotation.Nullable OffsetDateTime lockedDate) {
    this.lockedDate = JsonNullable.<OffsetDateTime>of(lockedDate);
    return this;
  }

  /**
   * Get lockedDate
   * @return lockedDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getLockedDate() {
        return lockedDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOCKED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getLockedDate_JsonNullable() {
    return lockedDate;
  }
  
  @JsonProperty(JSON_PROPERTY_LOCKED_DATE)
  public void setLockedDate_JsonNullable(JsonNullable<OffsetDateTime> lockedDate) {
    this.lockedDate = lockedDate;
  }

  public void setLockedDate(@jakarta.annotation.Nullable OffsetDateTime lockedDate) {
    this.lockedDate = JsonNullable.<OffsetDateTime>of(lockedDate);
  }


  public TestPlanWithAnalyticModel lockedById(@jakarta.annotation.Nullable UUID lockedById) {
    this.lockedById = JsonNullable.<UUID>of(lockedById);
    return this;
  }

  /**
   * Get lockedById
   * @return lockedById
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public UUID getLockedById() {
        return lockedById.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOCKED_BY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getLockedById_JsonNullable() {
    return lockedById;
  }
  
  @JsonProperty(JSON_PROPERTY_LOCKED_BY_ID)
  public void setLockedById_JsonNullable(JsonNullable<UUID> lockedById) {
    this.lockedById = lockedById;
  }

  public void setLockedById(@jakarta.annotation.Nullable UUID lockedById) {
    this.lockedById = JsonNullable.<UUID>of(lockedById);
  }


  public TestPlanWithAnalyticModel tags(@jakarta.annotation.Nullable List<TagModel> tags) {
    this.tags = JsonNullable.<List<TagModel>>of(tags);
    return this;
  }

  public TestPlanWithAnalyticModel addTagsItem(TagModel tagsItem) {
    if (this.tags == null || !this.tags.isPresent()) {
      this.tags = JsonNullable.<List<TagModel>>of(new ArrayList<>());
    }
    try {
      this.tags.get().add(tagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public List<TagModel> getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<TagModel>> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<List<TagModel>> tags) {
    this.tags = tags;
  }

  public void setTags(@jakarta.annotation.Nullable List<TagModel> tags) {
    this.tags = JsonNullable.<List<TagModel>>of(tags);
  }


  public TestPlanWithAnalyticModel startDate(@jakarta.annotation.Nullable OffsetDateTime startDate) {
    this.startDate = JsonNullable.<OffsetDateTime>of(startDate);
    return this;
  }

  /**
   * Used for analytics
   * @return startDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getStartDate() {
        return startDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getStartDate_JsonNullable() {
    return startDate;
  }
  
  @JsonProperty(JSON_PROPERTY_START_DATE)
  public void setStartDate_JsonNullable(JsonNullable<OffsetDateTime> startDate) {
    this.startDate = startDate;
  }

  public void setStartDate(@jakarta.annotation.Nullable OffsetDateTime startDate) {
    this.startDate = JsonNullable.<OffsetDateTime>of(startDate);
  }


  public TestPlanWithAnalyticModel endDate(@jakarta.annotation.Nullable OffsetDateTime endDate) {
    this.endDate = JsonNullable.<OffsetDateTime>of(endDate);
    return this;
  }

  /**
   * Used for analytics
   * @return endDate
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public OffsetDateTime getEndDate() {
        return endDate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getEndDate_JsonNullable() {
    return endDate;
  }
  
  @JsonProperty(JSON_PROPERTY_END_DATE)
  public void setEndDate_JsonNullable(JsonNullable<OffsetDateTime> endDate) {
    this.endDate = endDate;
  }

  public void setEndDate(@jakarta.annotation.Nullable OffsetDateTime endDate) {
    this.endDate = JsonNullable.<OffsetDateTime>of(endDate);
  }


  public TestPlanWithAnalyticModel description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public TestPlanWithAnalyticModel build(@jakarta.annotation.Nullable String build) {
    this.build = JsonNullable.<String>of(build);
    return this;
  }

  /**
   * Get build
   * @return build
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getBuild() {
        return build.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BUILD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBuild_JsonNullable() {
    return build;
  }
  
  @JsonProperty(JSON_PROPERTY_BUILD)
  public void setBuild_JsonNullable(JsonNullable<String> build) {
    this.build = build;
  }

  public void setBuild(@jakarta.annotation.Nullable String build) {
    this.build = JsonNullable.<String>of(build);
  }


  public TestPlanWithAnalyticModel productName(@jakarta.annotation.Nullable String productName) {
    this.productName = JsonNullable.<String>of(productName);
    return this;
  }

  /**
   * Get productName
   * @return productName
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public String getProductName() {
        return productName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getProductName_JsonNullable() {
    return productName;
  }
  
  @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
  public void setProductName_JsonNullable(JsonNullable<String> productName) {
    this.productName = productName;
  }

  public void setProductName(@jakarta.annotation.Nullable String productName) {
    this.productName = JsonNullable.<String>of(productName);
  }


  public TestPlanWithAnalyticModel hasAutomaticDurationTimer(@jakarta.annotation.Nullable Boolean hasAutomaticDurationTimer) {
    this.hasAutomaticDurationTimer = JsonNullable.<Boolean>of(hasAutomaticDurationTimer);
    return this;
  }

  /**
   * Get hasAutomaticDurationTimer
   * @return hasAutomaticDurationTimer
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getHasAutomaticDurationTimer() {
        return hasAutomaticDurationTimer.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HAS_AUTOMATIC_DURATION_TIMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getHasAutomaticDurationTimer_JsonNullable() {
    return hasAutomaticDurationTimer;
  }
  
  @JsonProperty(JSON_PROPERTY_HAS_AUTOMATIC_DURATION_TIMER)
  public void setHasAutomaticDurationTimer_JsonNullable(JsonNullable<Boolean> hasAutomaticDurationTimer) {
    this.hasAutomaticDurationTimer = hasAutomaticDurationTimer;
  }

  public void setHasAutomaticDurationTimer(@jakarta.annotation.Nullable Boolean hasAutomaticDurationTimer) {
    this.hasAutomaticDurationTimer = JsonNullable.<Boolean>of(hasAutomaticDurationTimer);
  }


  /**
   * Return true if this TestPlanWithAnalyticModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestPlanWithAnalyticModel testPlanWithAnalyticModel = (TestPlanWithAnalyticModel) o;
    return Objects.equals(this.analytic, testPlanWithAnalyticModel.analytic) &&
        Objects.equals(this.status, testPlanWithAnalyticModel.status) &&
        Objects.equals(this.createdById, testPlanWithAnalyticModel.createdById) &&
        Objects.equals(this.globalId, testPlanWithAnalyticModel.globalId) &&
        Objects.equals(this.isDeleted, testPlanWithAnalyticModel.isDeleted) &&
        Objects.equals(this.id, testPlanWithAnalyticModel.id) &&
        Objects.equals(this.name, testPlanWithAnalyticModel.name) &&
        Objects.equals(this.projectId, testPlanWithAnalyticModel.projectId) &&
        Objects.equals(this.attributes, testPlanWithAnalyticModel.attributes) &&
        equalsNullable(this.startedOn, testPlanWithAnalyticModel.startedOn) &&
        equalsNullable(this.completedOn, testPlanWithAnalyticModel.completedOn) &&
        equalsNullable(this.createdDate, testPlanWithAnalyticModel.createdDate) &&
        equalsNullable(this.modifiedDate, testPlanWithAnalyticModel.modifiedDate) &&
        equalsNullable(this.modifiedById, testPlanWithAnalyticModel.modifiedById) &&
        equalsNullable(this.lockedDate, testPlanWithAnalyticModel.lockedDate) &&
        equalsNullable(this.lockedById, testPlanWithAnalyticModel.lockedById) &&
        equalsNullable(this.tags, testPlanWithAnalyticModel.tags) &&
        equalsNullable(this.startDate, testPlanWithAnalyticModel.startDate) &&
        equalsNullable(this.endDate, testPlanWithAnalyticModel.endDate) &&
        equalsNullable(this.description, testPlanWithAnalyticModel.description) &&
        equalsNullable(this.build, testPlanWithAnalyticModel.build) &&
        equalsNullable(this.productName, testPlanWithAnalyticModel.productName) &&
        equalsNullable(this.hasAutomaticDurationTimer, testPlanWithAnalyticModel.hasAutomaticDurationTimer);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(analytic, status, createdById, globalId, isDeleted, id, name, projectId, attributes, hashCodeNullable(startedOn), hashCodeNullable(completedOn), hashCodeNullable(createdDate), hashCodeNullable(modifiedDate), hashCodeNullable(modifiedById), hashCodeNullable(lockedDate), hashCodeNullable(lockedById), hashCodeNullable(tags), hashCodeNullable(startDate), hashCodeNullable(endDate), hashCodeNullable(description), hashCodeNullable(build), hashCodeNullable(productName), hashCodeNullable(hasAutomaticDurationTimer));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestPlanWithAnalyticModel {\n");
    sb.append("    analytic: ").append(toIndentedString(analytic)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdById: ").append(toIndentedString(createdById)).append("\n");
    sb.append("    globalId: ").append(toIndentedString(globalId)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    startedOn: ").append(toIndentedString(startedOn)).append("\n");
    sb.append("    completedOn: ").append(toIndentedString(completedOn)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    modifiedById: ").append(toIndentedString(modifiedById)).append("\n");
    sb.append("    lockedDate: ").append(toIndentedString(lockedDate)).append("\n");
    sb.append("    lockedById: ").append(toIndentedString(lockedById)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    build: ").append(toIndentedString(build)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    hasAutomaticDurationTimer: ").append(toIndentedString(hasAutomaticDurationTimer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

