/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.testit.client.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import ru.testit.client.model.WorkflowShortApiResult;
import ru.testit.client.model.WorkflowShortApiResultGroup;
import ru.testit.client.model.WorkflowShortApiResultGroupedReply;
import ru.testit.client.model.WorkflowShortApiResultReply;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import ru.testit.client.invoker.JSON;

import com.fasterxml.jackson.core.type.TypeReference;

import jakarta.ws.rs.core.GenericType;
import jakarta.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import ru.testit.client.invoker.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.11.0")
@JsonDeserialize(using = WorkflowShortApiResultIReply.WorkflowShortApiResultIReplyDeserializer.class)
@JsonSerialize(using = WorkflowShortApiResultIReply.WorkflowShortApiResultIReplySerializer.class)
public class WorkflowShortApiResultIReply extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(WorkflowShortApiResultIReply.class.getName());

    public static class WorkflowShortApiResultIReplySerializer extends StdSerializer<WorkflowShortApiResultIReply> {
        public WorkflowShortApiResultIReplySerializer(Class<WorkflowShortApiResultIReply> t) {
            super(t);
        }

        public WorkflowShortApiResultIReplySerializer() {
            this(null);
        }

        @Override
        public void serialize(WorkflowShortApiResultIReply value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class WorkflowShortApiResultIReplyDeserializer extends StdDeserializer<WorkflowShortApiResultIReply> {
        public WorkflowShortApiResultIReplyDeserializer() {
            this(WorkflowShortApiResultIReply.class);
        }

        public WorkflowShortApiResultIReplyDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public WorkflowShortApiResultIReply deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize WorkflowShortApiResultReply
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WorkflowShortApiResultReply.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WorkflowShortApiResultReply'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WorkflowShortApiResultReply'", e);
            }

            // deserialize WorkflowShortApiResultGroupedReply
            try {
                boolean attemptParsing = true;
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WorkflowShortApiResultGroupedReply.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WorkflowShortApiResultGroupedReply'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WorkflowShortApiResultGroupedReply'", e);
            }

            if (match == 1) {
                WorkflowShortApiResultIReply ret = new WorkflowShortApiResultIReply();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for WorkflowShortApiResultIReply: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public WorkflowShortApiResultIReply getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "WorkflowShortApiResultIReply cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public WorkflowShortApiResultIReply() {
        super("oneOf", Boolean.FALSE);
    }

    public WorkflowShortApiResultIReply(WorkflowShortApiResultReply o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public WorkflowShortApiResultIReply(WorkflowShortApiResultGroupedReply o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("WorkflowShortApiResultGroupedReply", new GenericType<WorkflowShortApiResultGroupedReply>() {
        });
        schemas.put("WorkflowShortApiResultReply", new GenericType<WorkflowShortApiResultReply>() {
        });
        JSON.registerDescendants(WorkflowShortApiResultIReply.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return WorkflowShortApiResultIReply.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * WorkflowShortApiResultGroupedReply, WorkflowShortApiResultReply
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(WorkflowShortApiResultReply.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(WorkflowShortApiResultGroupedReply.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be WorkflowShortApiResultGroupedReply, WorkflowShortApiResultReply");
    }

    /**
     * Get the actual instance, which can be the following:
     * WorkflowShortApiResultGroupedReply, WorkflowShortApiResultReply
     *
     * @return The actual instance (WorkflowShortApiResultGroupedReply, WorkflowShortApiResultReply)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `WorkflowShortApiResultReply`. If the actual instance is not `WorkflowShortApiResultReply`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WorkflowShortApiResultReply`
     * @throws ClassCastException if the instance is not `WorkflowShortApiResultReply`
     */
    public WorkflowShortApiResultReply getWorkflowShortApiResultReply() throws ClassCastException {
        return (WorkflowShortApiResultReply)super.getActualInstance();
    }

    /**
     * Get the actual instance of `WorkflowShortApiResultGroupedReply`. If the actual instance is not `WorkflowShortApiResultGroupedReply`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WorkflowShortApiResultGroupedReply`
     * @throws ClassCastException if the instance is not `WorkflowShortApiResultGroupedReply`
     */
    public WorkflowShortApiResultGroupedReply getWorkflowShortApiResultGroupedReply() throws ClassCastException {
        return (WorkflowShortApiResultGroupedReply)super.getActualInstance();
    }

}

