/*
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.testit.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
/**
 * TestPointShortModel
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-07-05T10:40:26.135191+03:00[Europe/Moscow]")
public class TestPointShortModel {
  @SerializedName("testSuiteId")
  private UUID testSuiteId = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("testerId")
  private UUID testerId = null;

  @SerializedName("workItemId")
  private UUID workItemId = null;

  @SerializedName("configurationId")
  private UUID configurationId = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("lastTestResultId")
  private UUID lastTestResultId = null;

  @SerializedName("iterationId")
  private UUID iterationId = null;

  public TestPointShortModel testSuiteId(UUID testSuiteId) {
    this.testSuiteId = testSuiteId;
    return this;
  }

   /**
   * Get testSuiteId
   * @return testSuiteId
  **/
  @Schema(example = "9891bb36-71eb-4a4a-a049-eae838db9514", description = "")
  public UUID getTestSuiteId() {
    return testSuiteId;
  }

  public void setTestSuiteId(UUID testSuiteId) {
    this.testSuiteId = testSuiteId;
  }

  public TestPointShortModel id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "9891bb36-71eb-4a4a-a049-eae838db9514", description = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public TestPointShortModel testerId(UUID testerId) {
    this.testerId = testerId;
    return this;
  }

   /**
   * Get testerId
   * @return testerId
  **/
  @Schema(example = "9891bb36-71eb-4a4a-a049-eae838db9514", description = "")
  public UUID getTesterId() {
    return testerId;
  }

  public void setTesterId(UUID testerId) {
    this.testerId = testerId;
  }

  public TestPointShortModel workItemId(UUID workItemId) {
    this.workItemId = workItemId;
    return this;
  }

   /**
   * Get workItemId
   * @return workItemId
  **/
  @Schema(example = "9891bb36-71eb-4a4a-a049-eae838db9514", description = "")
  public UUID getWorkItemId() {
    return workItemId;
  }

  public void setWorkItemId(UUID workItemId) {
    this.workItemId = workItemId;
  }

  public TestPointShortModel configurationId(UUID configurationId) {
    this.configurationId = configurationId;
    return this;
  }

   /**
   * Get configurationId
   * @return configurationId
  **/
  @Schema(example = "9891bb36-71eb-4a4a-a049-eae838db9514", description = "")
  public UUID getConfigurationId() {
    return configurationId;
  }

  public void setConfigurationId(UUID configurationId) {
    this.configurationId = configurationId;
  }

  public TestPointShortModel status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Applies one of these values: Blocked, NoResults, Failed, Passed
   * @return status
  **/
  @Schema(example = "NoResult", description = "Applies one of these values: Blocked, NoResults, Failed, Passed")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public TestPointShortModel lastTestResultId(UUID lastTestResultId) {
    this.lastTestResultId = lastTestResultId;
    return this;
  }

   /**
   * Get lastTestResultId
   * @return lastTestResultId
  **/
  @Schema(example = "9891bb36-71eb-4a4a-a049-eae838db9514", description = "")
  public UUID getLastTestResultId() {
    return lastTestResultId;
  }

  public void setLastTestResultId(UUID lastTestResultId) {
    this.lastTestResultId = lastTestResultId;
  }

  public TestPointShortModel iterationId(UUID iterationId) {
    this.iterationId = iterationId;
    return this;
  }

   /**
   * Get iterationId
   * @return iterationId
  **/
  @Schema(example = "9891bb36-71eb-4a4a-a049-eae838db9514", description = "")
  public UUID getIterationId() {
    return iterationId;
  }

  public void setIterationId(UUID iterationId) {
    this.iterationId = iterationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestPointShortModel testPointShortModel = (TestPointShortModel) o;
    return Objects.equals(this.testSuiteId, testPointShortModel.testSuiteId) &&
        Objects.equals(this.id, testPointShortModel.id) &&
        Objects.equals(this.testerId, testPointShortModel.testerId) &&
        Objects.equals(this.workItemId, testPointShortModel.workItemId) &&
        Objects.equals(this.configurationId, testPointShortModel.configurationId) &&
        Objects.equals(this.status, testPointShortModel.status) &&
        Objects.equals(this.lastTestResultId, testPointShortModel.lastTestResultId) &&
        Objects.equals(this.iterationId, testPointShortModel.iterationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testSuiteId, id, testerId, workItemId, configurationId, status, lastTestResultId, iterationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestPointShortModel {\n");
    
    sb.append("    testSuiteId: ").append(toIndentedString(testSuiteId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    testerId: ").append(toIndentedString(testerId)).append("\n");
    sb.append("    workItemId: ").append(toIndentedString(workItemId)).append("\n");
    sb.append("    configurationId: ").append(toIndentedString(configurationId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastTestResultId: ").append(toIndentedString(lastTestResultId)).append("\n");
    sb.append("    iterationId: ").append(toIndentedString(iterationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
