name: Custom Attribute Model Validation

on:
  pull_request:
    branches: [ "*" ]
    paths:
      - 'src/main/java/ru/testit/client/model/CustomAttributeModel.java'

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-custom-attribute-model:
    runs-on: ubuntu-latest
    name: Validate CustomAttributeModel Fields

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for required fields in CustomAttributeModel
      run: |
        echo "Checking for required fields in CustomAttributeModel.java..."
        
        FILE_PATH="src/main/java/ru/testit/client/model/CustomAttributeModel.java"
        
        if [ ! -f "$FILE_PATH" ]; then
          echo "❌ CustomAttributeModel.java file not found!"
          exit 1
        fi
        
        echo "✅ File found: $FILE_PATH"
        
        # Check for workItemUsage field
        if grep -q "workItemUsage" "$FILE_PATH"; then
          echo "✅ Field 'workItemUsage' found"
          WORKITEM_COUNT=$(grep -c "workItemUsage" "$FILE_PATH")
          echo "   Number of mentions: $WORKITEM_COUNT"
        else
          echo "❌ Field 'workItemUsage' not found in file!"
          exit 1
        fi
        
        # Check for testPlanUsage field  
        if grep -q "testPlanUsage" "$FILE_PATH"; then
          echo "✅ Field 'testPlanUsage' found"
          TESTPLAN_COUNT=$(grep -c "testPlanUsage" "$FILE_PATH")
          echo "   Number of mentions: $TESTPLAN_COUNT"
        else
          echo "❌ Field 'testPlanUsage' not found in file!"
          exit 1
        fi
        
        # Check for field declarations specifically
        if grep -q "private.*workItemUsage" "$FILE_PATH"; then
          echo "✅ Field declaration 'workItemUsage' found"
        else
          echo "❌ Field declaration 'workItemUsage' not found!"
          exit 1
        fi
        
        if grep -q "private.*testPlanUsage" "$FILE_PATH"; then
          echo "✅ Field declaration 'testPlanUsage' found"
        else
          echo "❌ Field declaration 'testPlanUsage' not found!"
          exit 1
        fi
        
        echo ""
        echo "🎉 All required fields are present in CustomAttributeModel.java!"
        echo "📋 Verified fields:"
        echo "   - workItemUsage (mentions: $WORKITEM_COUNT)"
        echo "   - testPlanUsage (mentions: $TESTPLAN_COUNT)"
       